# Required to run your project under the correct environment.
language: php

sudo: required
dist: trusty

# Versions of PHP you want your project run with.
php:
  - 7.0
  - 7.1

mysql:
  database: wordpress_test
  username: root
  encoding: utf8

addons:
  chrome: stable

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  # Install php7 and relevant dependancies for the project 
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes apache2 libapache2-mod-php7.0 php7.0-curl php7.0-mysql php7.0-intl
  - sudo /etc/init.d/apache2 restart
  # Disables xdebug for faster performance
  - phpenv config-rm xdebug.ini
  # Create mysql database for the wordpress site
  - mysql -e 'create database wordpress_test'
  # Install chrome driver for selenium server 
  #- sudo wget https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip -P /usr/local/share
  #- sudo unzip /usr/local/share/chromedriver_linux64.zip -d /usr/local/share
  #- sudo rm /usr/local/share/chromedriver_linux64.zip
  # Install selenium web driver and give it 5 seconds as it needs some time to start up in order to not fail the build
  #- sh -e /etc/init.d/xvfb start
  #- export DISPLAY=:99.0 
  #- wget http://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.1.jar
  #- java -Dwebdriver.chrome.driver=/usr/local/share/chromedriver -jar selenium-server-standalone-3.9.1.jar > /dev/null &
  #- sleep 5

# Commands you want to run that will verify your build.
script: vendor/bin/behat features/login_test.feature

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 7.1
    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
